version: 1.0.{build}
image: Ubuntu
environment:
  API_URL: http://localhost:3333/v1
install:
  - sh: npm ci
build: off
test_script:
  - sh: npm run test
on_success:
  - sh: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov

      chmod +x codecov
      ./codecov
